<?php
	$keyId = 'rzp_test_9m2Yz2jjvmp6tQ';

?>

<form action = "https://www.example.com/payment/success/" method="POST">
<script 
	src = "https://rzp.io/l/8B0W9psLrZ"

	data-key="<?php echo $keyId; ?>" // Enter the Test API Key ID generated from Dashboard Settings →→ API Keys

	
	data-amount="<?php echo $result * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35. 

	data currency="INR"//You can accept international payments by changing the currency code. Contact our Support enable International for your account

	data-id="<?php echo 'OID'.rand(10,100).'END'; ?>"//Replace with the order_id generated by you in the backend. 

	data-buttontext="Pay with Razorpay"

	data-name="Pramod Bhosale"

	data-description="Digital payment for public buses"

	 data-image="https://example.com/your_logo.jpg"

	 data-prefill.name="<?php echo $_POST['name'];?>"

	data-prefill.email="<?php echo $_POST['email'];?>"
	data-prefill.email="<?php echo $_POST['PhoneNo'];?>"

	 data-theme.color="#F37254"

></script>
	<input type="hidden" custom ="Hidden Element" name="hidden">
</form>


